#!/bin/bash
Phrase="Please enter your choice. Do you want to install Python?: "
variants=("Yes" "No" "Quit")
select opt in "${variants[@]}"
do
    case $opt in
        "Yes")
            echo "Python is installed"
            break
            ;;
        "No")
            echo "Left the door closed"
            break
            ;;
        "Quit")
            break
            ;;
        *) echo "Wrong choice!!!!!!!!  $REPLY";;
    esac
done

