#!/bin/bash
num_1=15
num_2=45
echo "Enter the number:"
read num
if [ "$num" -gt "$num_1" -a "$num" -lt "$num_2" ]
then
echo "You entered the number between 15 and 45"
else
echo "You entered the number lower 15 or upper 45 or equivalents"
fi
